/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package IPLAnalyser;

import org.junit.Test;

import static org.junit.Assert.*;

import org.junit.Assert;

import java.util.List;

public class IPLAnalyserTest {

	private static final String MOST_RUNS_CSV_FILE_PATH = "./src/test/resources/IPL2019FactsheetMostRuns.csv";
	private static final String MOST_WICKETS_CSV_FILE_PATH = "./src/test/resources/IPL2019FactsheetMostWkts.csv";

	@Test
	public void givenMostRunsCSVFile_ShouldReturnTopBattingAverage() throws IPLException {
		IPLAnalyser iplAnalyser = new IPLAnalyser();
		List<IPLMostRunsCSV> battingList = iplAnalyser.loadBattingData(MOST_RUNS_CSV_FILE_PATH);
		iplAnalyser.sortByBattingAverage(battingList);
		Assert.assertEquals("MS Dhoni", battingList.get(0).playerName);
	}
	
	@Test
	public void givenMostRunsCSVFile_ShouldReturnTopStrikeRate() throws IPLException {
		IPLAnalyser iplAnalyser = new IPLAnalyser();
		List<IPLMostRunsCSV> battingList = iplAnalyser.loadBattingData(MOST_RUNS_CSV_FILE_PATH);
		iplAnalyser.sortByStrikeRate(battingList);
		Assert.assertEquals("Ishant Sharma", battingList.get(0).playerName);
	}
	
}
